# Generated by Django 4.2.18 on 2025-04-10 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0006_networksettings_default_ap_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('space_id', models.CharField(default='admin', max_length=100)),
                ('space_status', models.CharField(default='admin', max_length=100)),
            ],
        ),
    ]
