# Generated by Django 4.2.20 on 2025-04-08 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0006_networksettings_default_ap_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpaceInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spaceID', models.TextField()),
                ('spaceStatus', models.TextField()),
                ('previousSpaceStatus', models.TextField()),
                ('licenseFrameBase64', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='deviceID',
            field=models.CharField(default='000', max_length=100),
        ),
    ]
