# Generated by Django 4.2.20 on 2025-04-08 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0007_spaceinfo_account_deviceid'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceinfo',
            name='downleft',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='spaceinfo',
            name='downright',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='spaceinfo',
            name='topleft',
            field=models.TextField(default=0),
        ),
        migrations.AddField(
            model_name='spaceinfo',
            name='topright',
            field=models.TextField(default=0),
        ),
    ]
