# Generated by Django 4.2.18 on 2025-04-15 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0007_spaceinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='device_id',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
