# Generated by Django 4.2.20 on 2025-04-08 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0008_spaceinfo_downleft_spaceinfo_downright_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='spaceinfo',
            name='spaceFrame',
            field=models.TextField(default=''),
        ),
    ]
