# Generated by Django 4.2.20 on 2025-05-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0008_account_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksettings',
            name='server_ip',
            field=models.GenericIPAddressField(default='192.168.1.18'),
        ),
        migrations.AlterField(
            model_name='networksettings',
            name='server_port',
            field=models.PositiveIntegerField(default=1883),
        ),
    ]
