# Generated by Django 4.2.20 on 2025-05-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0009_alter_networksettings_server_ip_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksettings',
            name='server_port',
            field=models.PositiveIntegerField(default=1883),
        ),
    ]
