# Generated by Django 4.2.20 on 2025-04-08 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0009_spaceinfo_spaceframe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spaceinfo',
            name='spaceFrame',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
