# Generated by Django 4.2.20 on 2025-05-17 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0010_alter_networksettings_server_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='device_id',
            field=models.CharField(default='1001', max_length=100),
        ),
    ]
