# Generated by Django 4.2.20 on 2025-04-08 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0010_alter_spaceinfo_spaceframe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='spaceinfo',
            old_name='licenseFrameBase64',
            new_name='licensePlate',
        ),
    ]
