# Generated by Django 4.2.20 on 2025-06-05 05:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0011_alter_account_device_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksettings',
            name='server_ip',
            field=models.GenericIPAddressField(default='192.168.1.19'),
        ),
        migrations.CreateModel(
            name='DeviceBackground',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=100)),
                ('slot_index', models.IntegerField()),
                ('background_image', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('device_id', 'slot_index')},
            },
        ),
    ]
