# Generated by Django 4.2.20 on 2025-06-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cpgsapp', '0012_alter_networksettings_server_ip_devicebackground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networksettings',
            name='server_ip',
            field=models.GenericIPAddressField(default='192.168.1.10'),
        ),
    ]
